---
title: "Week07_Homework"
author: "Kassandra Jensen"
date: "2024-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Directions
You need to make a map using RMarkdown with one of the following datasets from past Tidy Tuesdays. Make sure, as usual, that you scripts and output are saved appropriately.

Plastic pollution, Cats on the move!, Where is Bigfoot!, Meteorites

# Load Libraries
```{r}
library(tidytuesdayR)
library(ggmap)
library(tidyverse)
library(here)
library(ggspatial)
```

# Load data: Cats on the move!
```{r}
tuesdata <- tidytuesdayR::tt_load('2023-01-31')
tuesdata <- tidytuesdayR::tt_load(2023, week = 5)

cats_uk <- tuesdata$cats_uk
cats_uk_reference <- tuesdata$cats_uk_reference

glimpse(cats_uk)
glimpse(cats_uk_reference)

cats_uk_full <- full_join(cats_uk, cats_uk_reference, by = "tag_id")

view(cats_uk_full)
```

```{r}
selected_cats <- c("Maverick", "Bear")

# Filter the dataset to only include the selected cats
cats_selected <- cats_uk_full %>% 
  filter(animal_id %in% selected_cats)

view(cats_selected)
```


```{r}
## Need to manually set location because UK map was too general. Pulled point from one of the cats.
UK_map <- get_map(location = c(lon = -5.081133, lat = 50.14673), zoom = 15, maptype = "hybrid")
ggmap(UK_map)

ggmap(UK_map) +
  geom_point(data = cats_selected,
             aes(x = location_long, 
                 y = location_lat, 
                 color = as.factor(animal_id)),
             size = 2) +
  geom_path(data = cats_selected %>% arrange(animal_id, timestamp),
            aes(x = location_long,
                y = location_lat, 
                group = animal_id, 
                color = as.factor(animal_id)),
            size = 0.5, lineend = "round") +
  labs(color = "Cat ID") +
  theme_minimal()

```

