---
title: "Week8b_Lecture: Advanced Plotting"
author: "Kassandra Jensen"
date: "2024-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}

library(tidyverse)
library(here)
library(patchwork) # for bringing plots together
library(ggrepel) # for repelling labels
library(gganimate) # animations
library(magick) # for images
library(palmerpenguins)
```
# Patchwork
```{r}
# plot 1
p1<-penguins %>%
  ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()
p1

# plot 2
p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)
p2

# Bring the plots together using simple operations.
p1+p2 #next to each other

p1/p2 #on top of one another

#Group the legends.
p1+p2 +
  plot_layout(guides = 'collect')

#Add labels (A,B).
p1+p2 +
  plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')

p1 | (p1 / p2) ## can make specific layouts
```
# GGRepel ## this is so helpful!!
```{r}
View(mtcars)

ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text() + # creates a text label
  geom_point(color = 'red')


# Repel the labels
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text_repel() + # repel them
  geom_point(color = 'red')

#Use the label function
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_label_repel() + # repel them
  geom_point(color = 'red')

## you can also make it point out only specific points
```
# GG animate
```{r}
# static plot
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()

## Add a transition
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition. # 2 seconds
     state_length = 1 # The length of the pause between transitions # how long it stays at transition # 1 second
   )

#Change the ease aesthetics
## other linear (default), bounce, sine, circular
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("bounce-in-out")

#Add a transition title
## see the year
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("sine-in-out") +
  labs(title = 'Year: {closest_state}')

#Save it as a .gif
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("sine-in-out") +
  labs(title = 'Year: {closest_state}') +
  anim_save(here("Week08","Output","mypengiungif.gif"))

```
# Magick: advanced image processing
```{r}
#Put a penguin in it.
#Read in an image of a pengiun (can be on your computer or the internet).

penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png")
penguin

#To put it on a plot you first need to save your plot as an image
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()

ggsave(here("Week08","Output","penguinplot.png"))

#Read in the plot as a magick image and make a composite plot
penplot<-image_read(here("Week08","Output","penguinplot.png"))
out <- image_composite(penplot, penguin, offset = "+70+30")

out


#You can do this with gifs too
# Read in a penguin gif
pengif<-image_read("https://media3.giphy.com/media/H4uE6w9G1uK4M/giphy.gif")
outgif <- image_composite(penplot, pengif, gravity = "center")
animation <- image_animate(outgif, fps = 10, optimize = TRUE)
animation
```
```{r}
# totally awesome r package

library(sourrr)
build_recipe(final_weight = 900, hydration = 0.75)
```















