---
title: "Week15bModels"
author: "Kassandra Jensen"
date: "2024-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Biblioteca
```{r}
library(tidyverse)
library(here)
library(palmerpenguins)
library(broom)
library(performance) 
library(modelsummary)
library(tidymodels)
library(wesanderson)
```

# Linear Model
```{r}
# Linear model of Bill depth ~ Bill length by species
Peng_mod<-lm(bill_length_mm ~ bill_depth_mm*species, data = penguins)

check_model(Peng_mod) # check assumptions of an lm model

# Two basic ways to look at the results
anova(Peng_mod)
summary(Peng_mod) ## effect size

# Tidy coefficients
coeffs<-tidy(Peng_mod) # just put tidy() around it
coeffs

#glance extracts R-squared, AICs, etc of the model
# tidy r2, etc
results<-glance(Peng_mod) 
results

#augment add residuals and predicted values to your original data and requires that you put both the model and data
# tidy residuals, etc
resid_fitted<-augment(Peng_mod)
resid_fitted
```

```{r}
#Export summary tables to word, markdown, or tex document. You can also modify the tables to make them pub quality.

#Let's compare the Peng_mod with one that does not have species as an interaction term.

# New model
Peng_mod_noX<-lm(bill_length_mm ~ bill_depth_mm, data = penguins)
#Make a list of models and name them
models<-list("Model with interaction" = Peng_mod,
             "Model with no interaction" = Peng_mod_noX)
#Save the results as a .docx
modelsummary(models, output = here("Week_13","output","table.docx"))

models

## Graph it
#install.packages(wesanderson)
modelplot(models) +
    labs(x = 'Coefficients', 
         y = 'Term names') +
    scale_color_manual(values = wes_palette('Darjeeling1'))
```
```{r}
 models<- penguins %>%
  ungroup()%>% # the penguin data are grouped so we need to ungroup them
    nest(.by = species) %>% # nest all the data by species 
  mutate(fit = map(data, ~lm(bill_length_mm~body_mass_g, data = .)))

models


 results<-models %>%
   mutate(coeffs = map(fit, tidy), # look at the coefficients
          modelresults = map(fit, glance)) %>% # R2 and others 
   select(species, coeffs, modelresults) %>% # only keep the results
   unnest() # put it back in a dataframe and specify which columns to unnest
view(results) 
```




