---
title: "Week_7_lecture"
author: "Kassandra Jensen"
date: "2024-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## La biblioteca
```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata) ## hasn't been updated since nov 2022
library(mapproj)

# Read in data on population in California by county
popdata<-read_csv(here("Week07","Data","CApopdata.csv"))
view(popdata)


#read in data on number of seastars at different field sites
stars<-read_csv(here("Week07","Data","stars.csv"))
view(stars)

# get data for the entire world
world<-map_data("world")
head(world)

# get data for the USA
usa<-map_data("usa")
head(usa)

states <- map_data("state") ### only US states for THIS package, there are other packages
head(states)


counties <- map_data("county")
counties


ggplot()+
  geom_polygon(data = world, 
               aes(x = long, y = lat, 
                group = group,
                fill= region), ## within aesthetics bc taken from data points
                color = "black")  + ### outside of aestetics bc set to color
                guides(fill = FALSE) + ### MUST include this with fill otherwise it just gives you a big legend
                theme(panel.background = element_rect(fill = "lightblue")) +
                coord_map(projection = "sinusoidal", ## "mercator" most commonly used projection type
            xlim = c(-180,180))      ## you can change these but looks kinda fuggged when you do

```
```{r}
## Filter out just the California data.

# Use the states dataset
CA_data<-states %>%
  filter(region == "california")
head(CA_data)

ggplot() +
  geom_polygon(data= CA_data, 
               aes(x= long, y= lat, 
                   group = group),
               color = "black",
               fill = "orange") +
              guides(fill = FALSE) +
   coord_map(projection = "mercator")

## wrangle the data. Make the column names the same to join the two datasets.
```

```{r}

#Plot the population of every county in California.

#First, we need to get the county level data and join it with our dataset on population (How do I do it?)
# Look at the county data
head(counties)[1:3,] # only showing the first 3 rows for space

# Look at the county data
head(popdata)

CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have same names in other state

head(CApop_county)

ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),
             color = "black")+
  coord_map()+
  theme_void()+
  scale_fill_gradient(trans = "log10") ### log transformed bc the other way was so representative of the population denisty before

```

```{r}
### add the stars in
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites ### DUDE you can use more than one data set in a graph!
             aes(x = long,
                 y = lat,
                 size = star_no))+ ## makes stars bigger
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10") +
  labs(size = "# stars/m2")

ggsave(here("Week07","Output","Lecture", "CApop.pdf"))

```

```{r}
#Total Awesome R package

library(ggdogs)
ggplot(mtcars) +
  geom_dog(aes(mpg, wt), dog = "pug", size = 5)


```

```{r}
### getting api
library(lubridate)
library(ggplot2)
library(dplyr)
library(data.table)
library(ggrepel)
library(tidyverse)


#A) Download the main crime incident dataset

incidents= read.csv('https://raw.githubusercontent.com/lgellis/MiscTutorial/master/ggmap/i2Sample.csv', stringsAsFactors = FALSE)

#B) Download the extra dataset with the most dangerous Seattle cities as per:

# https://housely.com/dangerous-neighborhoods-seattle/

n <- read.csv('https://raw.githubusercontent.com/lgellis/MiscTutorial/master/ggmap/n.csv', stringsAsFactors = FALSE)

# Look at the data sets

dim(incidents)

head(incidents)

attach(incidents)

dim(n)

head(n)

attach(n)

# Create some color variables for graphing later

col1 = "#011f4b"

col2 = "#6497b1"

col3 = "#b3cde0"

col4 = "#CC0000"

#add year to the incidents data frame
incidents$ymd <-mdy_hms(Event.Clearance.Date)
incidents$year <- year(incidents$ymd)

#Create a more manageable data frame with only 2017 and 2018 data
i2 <- incidents %>% 
  filter(year>=2017 & year<=2018)

#Only include complete cases
i2[complete.cases(i2), ]

#create a display label to the n data frame (dangerous neighbourhoods)
n$label <-paste(Rank, Location, sep="-")
```
```{r}


#Get the latest Install
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup", force=TRUE)

#Load the library
library("ggmap")

#Set your API Key
ggmap::register_google(key = "AIzaSyAYy-dqjsUwnvE59TStdRRQQv6hYqrdmzw")

```


