---
title: "Week 9a"
author: "Kassandra Jensen"
date: "2024-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
## we don't need any packages to make functions -- it's in base R 
## it's good to keep functions up top or in another script to keep things clean and more organized
## can load custom functions with ##source(here("code_script.rmd/csv"))
```
```{r}
## Make your own data frame
df <- tibble(
  a = rnorm(10), # draws 10 random values from a normal distribution
  b = rnorm(10),
  c = rnorm(10),
  d = rnorm(10)
)
head(df)

## Anytime you have to do a task more then once...
## Let's use an example where we want to rescale data in multiple columns (value - min/(max - min))
## Rescale every column individually

df<-df %>%
  mutate(a = (a-min(a, na.rm = TRUE))/(max(a, na.rm = TRUE)-min(a, na.rm = TRUE)))

## Now copy and paste the same code for each column without making any mistakes

df<-df %>%
  mutate(a = (a-min(a, na.rm = TRUE))/(max(a, na.rm = TRUE)-min(a, na.rm = TRUE)),
         b = (b-min(b, na.rm = TRUE))/(max(b, na.rm = TRUE)-min(b, na.rm = TRUE)), ## this had a mistake but i fixed it 
         c = (c-min(c, na.rm = TRUE))/(max(c, na.rm = TRUE)-min(c, na.rm = TRUE)),
         d = (d-min(d, na.rm = TRUE))/(max(d, na.rm = TRUE)-min(d, na.rm = TRUE)))

## We can write a function for this

rescale01 <- function(x) {
  value<-(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))
  return(value)
}

df %>%
  mutate(a = rescale01(a),
         b = rescale01(b),
         c = rescale01(c),
         d = rescale01(d))

```
```{r}
## Let's make a function to covert degrees fahrenheit to celcius.

## What is the calculation for F to C?

temp_C <- (temp_F - 32) * 5 / 9

## make it a funciton:
fahrenheit_to_celsius <- function(temp_F) ## what value we want it to take
  {
  temp_C <- (temp_F - 32) * 5 / 9 ## function
  return(temp_C)   ## what we wat it to return
}

fahrenheit_to_celsius(5)


## now do it for kelvin
celcius_to_kelvin <- function(temp_C) {
  temp_K <- (temp_C + 273.15)
  return(temp_K)
}

celcius_to_kelvin(10)

```

```{r}
library(palmerpenguins)
library(PNWColors) # for the PNW color palette 
# you may need to install the PNWColors library if you haven't used it yet

pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 

ggplot(penguins, aes(x = body_mass_g, y = bill_length_mm, color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and another example of how to manually change the legend title for colors
  theme_bw()


## Name and set up function
## you don't need a return in this case 

myplot<-function(data, x, y){
pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 
ggplot(data, aes(x = {{x}}, y = {{y}}, color = island))+  ## have to add the curly brackets to help us assign variables that are column names in dataframes
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}

myplot(data = penguins, x = body_mass_g, y = bill_length_mm)

#Test with new variables

myplot(data = penguins, x = body_mass_g, y = flipper_length_mm)


## addign defaults
##Let's say you want to create a default for the function to always default to the penguins dataset. You can set those directly in the function.

myplot<-function(data = penguins, x, y){
pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}

myplot(x = body_mass_g, y = flipper_length_mm)

## You can also layer onto your plot using '+' just like it is a regular ggplot to change things like labels.

myplot(x = body_mass_g, y = flipper_length_mm)+
  labs(x = "Body mass (g)",
       y = "Flipper length (mm)")
```
# If-else statements
```{r}
## Imagine you want a variable to be equal to a certain value if a condition is met. This is a typical problem that requires the if ... else ... construct. For instance:

a <- 4
b <- 5

if (a > b) { # my question
  f <- 20 # if it is true give me answer 1
    } else { # else give me answer 2
  f <- 10
} 
  
f
```

# back to plotting
```{r}
## Using if...else... we can make our function even more flexible. Let's say we want the option of adding the geom_smooth lines. We can create a variable that if set to TRUE add the geom_smooth, otherwise print without.

## First add a new argument for lines and make the default TRUE for ease

myplot<-function(data = penguins, x, y ,lines=TRUE ){ # add new argument for lines
pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}


myplot<-function(data = penguins, x, y, lines=TRUE ){ # add new argument for lines
pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 
if(lines==TRUE){
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}
else{
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}
}


myplot(x = body_mass_g, y = flipper_length_mm) ## lines = true is the default now
myplot(x = body_mass_g, y = flipper_length_mm, lines = FALSE)


```
# fun r package
```{r}
library(emokid)
iamsad()

iamlesssad()

mymood()
```





